version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    image: lukuvinkkikirjasto-dev
    container_name: lukuvinkkikirjasto-dev
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/lukuvinkkikirjasto
    
  db:
    build:
      context: ./
      dockerfile: ./db.Dockerfile
    container_name: lukuvinkkikirjasto-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
 
  test:
    build:
      context: ./
      dockerfile: ./devrobot.Dockerfile
    network_mode: host
    container_name: lukuvinkkikirjasto-test
    depends_on:
      - app
    profiles:
      - test
    image: robot
    shm_size: "256M"
    environment:
        USERNAME: Test
    volumes: [
        "$PWD/src/tests:/src/tests",
        "$PWD/scripts:/scripts",
        "$PWD/documentation/test_reports/robot:/documentation/test_reports/robot"
    ]
    
volumes:
  postgres-data:
